#!/bin/bash
echo "Building docker image..."
docker build -t alpcon .

if [ "$(docker ps | grep "AlpCon")" == "" ]; then
        echo "AlpCon is not running, starting now."
        docker run -d --rm -v ${WORKSPACE}/simple:/simple --name AlpCon alpcon
        sleep 10
else
        echo "AlpCon is already running. Please wait."
        exit 2

fi
if [ "$(docker ps | grep "AlpCon")" == "" ]; then
        echo "Program finished successfully! Action was logged to ${WORKSPACE}/simple/results"
        echo "Removing alpcon image."
	docker rmi -f alpcon
	echo "Done!"
        exit 0
else
	echo "Program failed (timed-out). Killing docker container."
        docker stop AlpCon
        echo "Removing alpcon image."
	docker rmi -f alpcon
	echo "Done!"
        exit 1
fi
